### ISSUE TITLE
docker部署后，每次重启容器，没有数据，需要重新安装

### ISSUE THREAD

**Issue by Halecoder** [easysoft/zentaopms#158]
### 描述 (Description)

下面为docker-compose文件
```yml
version: '2'

networks:
    zentao-net:
      driver: bridge

services:

# mysql service for zentao
  zentao-mysql:
    image: mariadb:10.4
    container_name: zentao-mysql
    ports:
      - '3307:3306'
    volumes:
      - './data/zentao_db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=zentao
    networks:
      - zentao-net

# redis service for zentao
#  zentao-redis:
#    image: redis:3.2.12-alpine3.8
#    container_name: zentao-redis
#    networks:
#      - zentao-net

# zentao service
  zentao:
    image: easysoft/zentao:18.0
    container_name: zentao
    ports:
      - '20080:80'
    volumes:
      - './data/zentao_data:/www/zentaopms'
    depends_on:
      - zentao-mysql
    environment:
      - ZT_MYSQL_HOST=zentao-mysql
      - ZT_MYSQL_PORT=3306
      - ZT_MYSQL_USER=root
      - ZT_MYSQL_PASSWORD=123456
      - ZT_MYSQL_DB=zentao
     # - PHP_SESSION_TYPE=redis
     # - PHP_SESSION_PATH=tcp://zentao-redis:6379
     # - PHP_REDIS_SENTINEL=1
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MAX_INPUT_VARS=2000
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      - PROTOCOL_TYPE=http
      - EASYSOFT_DEBUG=true
      - DEBUG=1
      - IS_CONTAINER=true
    networks:
      - zentao-net
```
部署成功
![image](https://github.com/user-attachments/assets/1fb50623-7e8f-4ac8-8926-0e7aeef20bed)

### 期望 (Expectation)

重启容器后能够保存数据，不需要再次安装初始化mysql数据

### 结果 (Result)

每次重启容器，都需要一遍mysql数据库初始化，进入数据库内部，只有数据库名，没有任何表和数据

每次都要进入下列页面

![image](https://github.com/user-attachments/assets/5e9961a2-9704-4825-9fd1-2da70f42c4e9)

打开数据库查看

![image](https://github.com/user-attachments/assets/74247734-bc9d-44f5-993f-21a0ec99a36e)

### 软件版本 (Software version)

18.0
